Repository goreleaser/chglog, pull requests merged in 2020-12, with the labels that each got.

#39 docs: fix install instructions
  README.md
Labels: size/XS

#42 feat: upgrade yaml
  files.go
  go.mod
  go.sum
Labels: automerge, enhancement, size/XS

#43 fix: tags that happened off the branch you were working on caused issues when generating the changelog
  .gitattributes
  .github/workflows/build.yml
  .goreleaser.yml
  add.go
  git.go
  go.mod
  go.sum
  init.go
  pkg/commands/add.go
Labels: size/L
